### PR TITLE
Update V compiler

### PR DESCRIPTION
**Pull request by keiravillekode**
We update to V version ~weekly.2023.48~ weekly.2024.22

### CODE REVIEW

**Comment by keiravillekode** [comment]
I have no idea what happened with those CI errors.

Regardless, let's wait a week for weekly.2023.49

https://github.com/exercism/vlang/pull/176

**Comment by ErikSchierboom** [comment]
> I have no idea what happened with those CI errors.

Well that's likely because the output of the newer compiler is slightly different from the old one. You'd just need to update the expected files in the test cases.

**Comment by hraftery** [comment]
> > I have no idea what happened with those CI errors.
> 
> Well that's likely because the output of the newer compiler is slightly different from the old one. You'd just need to update the expected files in the test cases.

You can see an example of what needs to be updated in [this PR](https://github.com/exercism/vlang-test-runner/pull/16/files) - it's the `expected_results.json` files, because the format of the results changes from time to time. In this case, it [looks like](https://github.com/exercism/vlang-test-runner/pull/39/checks) it's the one in `example-syntax-error` folder. Just confirm the differences are formatting only, and replace the `expected_results.json` file with the actual `results.json` file.

**Comment by keiravillekode** [comment]
I have fixed the issues. Now using weekly.2024.22

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
